databases:
  - name: test-deploy
    databaseName: test-deploy
    user: test-deploy

services:
  - type: web
    name: test-deploy
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: test-deploy
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
